@extends("layouts.main-teacher")

@section("title")
	<h1>Invoice & Reimburse</h1>
@endsection

@section('popup')
    <x-popup popup_title="Reimburse Evidence Photo" class="flex flex-col items-stretch justify-center w-11/12 xl:w-1/2" id="show-evidence-photo-popup">
        <div class="overflow-y-auto" style="max-height: 600px;">
            <img alt="N/A" class="w-full mt-2" id="reimburse-evidence-photo-src" style="object-fit: cover; object-position: center;">
        </div>
    </x-popup>
@endsection

@section("content")
    <x-section-container>
        <x-page-title>My Invoices and Reimburse</x-page-title>
        <div class="w-full bg-slate-400 mt-2 mb-3" style="height: 2px;"></div>

        @if(session()->has("success"))
			<x-badge-success badge_text="{{ session('success') }}"></x-badge-success>
		@elseif(session()->has("warning"))
			<x-badge-warning badge_text="{{ session('warning') }}"></x-badge-warning>
		@elseif(session()->has("danger"))
			<x-badge-danger badge_text="{{ session('danger') }}"></x-badge-danger>
		@endif

        <div class="w-full flex flex-wrap">
			<a href="{{ route('teacher.lecturer-invoice-reimburse.index',  ['content' => 'invoice']) }}"
				class="py-2 w-1/2 xl:w-1/6 sm:w-40 text-center hover:bg-slate-200"
				style="@if(request('content') == 'invoice' || !request('content')) border-bottom: 4px solid #1db9cf; @endif">
				Invoice
			</a>

			<a href="{{ route('teacher.lecturer-invoice-reimburse.index', ['content' => 'reimburse']) }}"
				class="py-2 w-1/2 xl:w-1/6 sm:w-40 text-center hover:bg-slate-200"
				style="@if(request('content') == 'reimburse') border-bottom: 4px solid #1db9cf; @endif">
				Reimburse
			</a>
        </div>

        @if(request('content') == 'invoice' || !request('content'))
            <div class="mt-6">
                <x-anchor-button href="{{ route('teacher.lecturer-invoice-reimburse.invoice.create') }}"><i class="bi bi-plus-lg"></i> New Invoice</x-anchor-button>
            </div>

            <div class="w-full overflow-auto hidden xl:block mt-3" style="height: 60vh;">
                <table class="w-full">
                    <thead>
                        <th class="text-start py-3 px-4 border-b-2 border-slate-400">Invoice Number</th>
                        <th class="text-start py-3 px-4 border-b-2 border-slate-400">Invoice Date</th>
                        <th class="text-start py-3 px-4 border-b-2 border-slate-400">Invoice Period</th>
                        <th class="text-start py-3 px-4 border-b-2 border-slate-400">Actions</th>
                    </thead>
                    <tbody>
                        @forelse(Auth::user()->lecturer_invoices()->orderBy('date', 'desc')->get() as $invoice)
                            @php
                                $invoice_date = Carbon\Carbon::parse($invoice->date);
                                $last_25th = $invoice_date->day >= 25 ? $invoice_date->day(25) : $invoice_date->subMonth()->day(25);
                                $last_26th = $last_25th->copy()->subMonth()->day(26);
                            @endphp

                            <tr class="@if($loop->iteration % 2 == 1) bg-white @endif">
                                <td class="py-3 px-4">Invoice {{ $invoice->number }}</td>
                                <td class="py-3 px-4">{{ Carbon\Carbon::parse($invoice->date)->format('D, d M Y') }}</td>
                                <td class="py-3 px-4">{{ $last_26th->format('d M Y') }} - {{ $last_25th->format('d M Y') }}</td>
                                <td class="py-3 px-4">
                                    <div class="flex gap-1">
                                        <a href="{{ route('teacher.lecturer-invoice-reimburse.invoice.edit', $invoice->id) }}" title="Edit Invoice Data">
                                            <img src="{{ asset('img/edit.svg') }}" alt="icon" class="max-w-8 min-w-8 max-h-8 min-h-8 hover:scale-110">
                                        </a>
                                        <a href="{{ route('teacher.lecturer-invoice-reimburse.invoice.download', $invoice->id) }}" title="Download Invoice (Generated by System)">
                                            <img src="{{ asset('img/download.svg') }}" alt="icon" class="max-w-8 min-w-8 max-h-8 min-h-8 hover:scale-110">
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @empty
                            <tr class="bg-white">
                                <td class="py-3 px-4 text-center" colspan="4">- No Invoices Data Yet In This Course -</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

            <div class="w-full flex flex-col gap-4 xl:hidden items-stretch mt-4">
				@forelse (Auth::user()->lecturer_invoices()->orderBy('date', 'desc')->get() as $invoice)
                    @php
                        $invoice_date = Carbon\Carbon::parse($invoice->date);
                        $last_25th = $invoice_date->day >= 25 ? $invoice_date->day(25) : $invoice_date->subMonth()->day(25);
                        $last_26th = $last_25th->copy()->subMonth()->day(26);
                    @endphp

					<div class="bg-white rounded-xl p-4 flex flex-col gap-3 dropdown-container">
						<button class="dropdown-toggler flex w-full justify-between items-center mb-2">
							<strong class="text-base text-start">Invoice {{ $invoice->number }}</strong>
							<i class="bi bi-chevron-down"></i>
						</button>
						<div class="flex flex-col w-full dropdown-menu" style="display: none;">
							<div class="flex flex-col">
                                <div>Invoice Date: {{ Carbon\Carbon::parse($invoice->date)->format('D, d M Y') }}</div>
                                <div>Invoice Period: {{ $last_26th->format('d M Y') }} - {{ $last_25th->format('d M Y') }}</div>

                                <span class="font-bold mt-4">Actions</span>
                                <div class="flex gap-3 mt-3">
                                    <a href="{{ route('teacher.lecturer-invoice-reimburse.invoice.edit', $invoice->id) }}" title="Edit Invoice Data">
                                        <img src="{{ asset('img/edit.svg') }}" alt="icon" class="max-w-8 min-w-8 max-h-8 min-h-8 hover:scale-110">
                                    </a>
                                    <a href="{{ route('teacher.lecturer-invoice-reimburse.invoice.download', $invoice->id) }}" title="Download Invoice (Generated by System)">
                                        <img src="{{ asset('img/download.svg') }}" alt="icon" class="max-w-8 min-w-8 max-h-8 min-h-8 hover:scale-110">
                                    </a>
                                </div>
							</div>
						</div>
					</div>
				@empty
					- N/A -
				@endforelse
			</div>
        @endif

        @if(request('content') == 'reimburse')
            <div class="mt-6">
                <x-anchor-button href="{{ route('teacher.lecturer-invoice-reimburse.reimburse.create') }}"><i class="bi bi-plus-lg"></i> New Reimburse</x-anchor-button>
            </div>

            <div class="w-full overflow-auto hidden xl:block mt-3" style="height: 60vh;">
                <table class="w-full">
                    <thead>
                        <th class="text-start py-3 px-4 border-b-2 border-slate-400">Date</th>
                        <th class="text-start py-3 px-4 border-b-2 border-slate-400">Need</th>
                        <th class="text-start py-3 px-4 border-b-2 border-slate-400">Amount</th>
                        <th class="text-start py-3 px-4 border-b-2 border-slate-400">Picture</th>
                        <th class="text-center py-3 px-4 border-b-2 border-slate-400">Actions</th>
                    </thead>
                    <tbody>
                        @forelse (Auth::user()->reimburses()->orderBy('date', 'desc')->get() as $reimburse)
                            <tr class="@if($loop->iteration % 2 == 1) bg-white @endif">
                                <td class="py-3 px-4">{{ Carbon\Carbon::parse($reimburse->date)->format('D, d M Y') }}</td>
                                <td class="py-3 px-4">{{ $reimburse->need }}</td>
                                <td class="py-3 px-4">Rp {{ number_format($reimburse->amount, 2, ',', '.') }}</td>
                                <td class="py-3 px-4">
                                    <img src="{{ Storage::url("app/public/" . $reimburse->evidence_path) }}" alt="evidence img" width="200px">
                                </td>
                                <td class="py-3 px-4">
                                    <div class="flex gap-1 w-full justify-center">
                                        <a href="{{ route('teacher.lecturer-invoice-reimburse.reimburse.edit', $reimburse->id) }}" title="Edit this reimburse data">
                                            <img src="{{ asset('img/edit.svg') }}" alt="icon" class="max-w-8 min-w-8 max-h-8 min-h-8 hover:scale-110">
                                        </a>
                                        <button type="button" data-src="{{ Storage::url("app/public/" . $reimburse->evidence_path) }}" class="show-evidence-photo-btn" title="Preview reimburse photo evidence">
                                            <img src="{{ asset('img/photo.svg') }}" alt="icon" class="max-w-8 min-w-8 max-h-8 min-h-8 hover:scale-110">
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        @empty
                            <tr class="bg-white">
                                <td class="py-3 px-4 text-center" colspan="5">- No Invoices Data Yet In This Course -</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

            <div class="w-full flex flex-col gap-4 xl:hidden items-stretch mt-4">
				@forelse (Auth::user()->reimburses()->orderBy('date', 'desc')->get() as $reimburse)
					<div class="bg-white rounded-xl p-4 flex flex-col gap-3 dropdown-container">
						<button class="dropdown-toggler flex w-full justify-between items-center mb-2">
							<div class="flex flex-col">
								<strong class="text-base text-start">{{ Carbon\Carbon::parse($reimburse->date)->format('D, d M Y') }}</strong>
                                <p>{{ $reimburse->need }}</p>
                            </div>
							<i class="bi bi-chevron-down"></i>
						</button>
						<div class="flex flex-col w-full dropdown-menu" style="display: none;">
							<div class="flex flex-col">
                                <div class="font-semibold">Amount: Rp {{ number_format($reimburse->amount, 2, ',', '.') }}</div>
								<img src="{{ Storage::url("app/public/" . $reimburse->evidence_path) }}" class="mt-4" width="200px" alt="photo">
                            
                                <span class="font-bold mt-4">Actions</span>
                                <div class="flex gap-1 w-full justify-start mt-3">
                                    <a href="{{ route('teacher.lecturer-invoice-reimburse.reimburse.edit', $reimburse->id) }}" title="Edit this reimburse data">
                                        <img src="{{ asset('img/edit.svg') }}" alt="icon" class="max-w-8 min-w-8 max-h-8 min-h-8 hover:scale-110">
                                    </a>
                                    <button type="button" data-src="{{ Storage::url("app/public/" . $reimburse->evidence_path) }}" class="show-evidence-photo-btn" title="Preview reimburse photo evidence">
                                        <img src="{{ asset('img/photo.svg') }}" alt="icon" class="max-w-8 min-w-8 max-h-8 min-h-8 hover:scale-110">
                                    </button>
                                </div>
							</div>
						</div>
					</div>
				@empty
					- N/A -
				@endforelse
			</div>
        @endif
    </x-section-container>

    <script>
        $(document).ready(() => {
            $('.show-evidence-photo-btn').on('click', function(){
                $('#reimburse-evidence-photo-src').attr('src', $(this).data('src'));
                $('#show-evidence-photo-popup').parent().show();
            });
        });
    </script>
@endsection